# Generated by Django 4.2.4 on 2023-08-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='homenav_drop',
            table='HomeNav_drop',
        ),
    ]
