# Generated by Django 4.2.4 on 2023-08-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0003_appdown_appfooter_appfooter1_gettouch_socialicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='media/')),
                ('heading', models.CharField(max_length=100)),
            ],
        ),
    ]
