# Generated by Django 4.2.3 on 2023-08-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0004_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='pre_registataion_QA_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pre_registataion_QA_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pre_registataion_QA_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pre_registataion_QA_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_4', models.CharField(max_length=100)),
            ],
        ),
    ]
