# Generated by Django 4.2.4 on 2023-08-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0007_homenav_drop_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('subtitle1', models.CharField(max_length=2000)),
                ('subtitle2', models.CharField(max_length=2000)),
                ('content1', models.CharField(max_length=2000)),
                ('content2', models.CharField(max_length=2000)),
                ('content3', models.CharField(max_length=2000)),
                ('content4', models.CharField(max_length=2000)),
                ('content5', models.CharField(max_length=2000)),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
