# Generated by Django 4.2.4 on 2023-08-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0008_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homenav_drop',
            options={'ordering': ['order'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
