# Generated by Django 4.2.4 on 2023-08-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0009_alter_homenav_drop_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homenav_drop',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelTable(
            name='homenav_drop',
            table=None,
        ),
    ]
