# Generated by Django 4.2.4 on 2023-08-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0011_additional_eligibility_additional_requirements_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blood',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='blood',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
