# Generated by Django 4.2.4 on 2023-08-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0015_delete_bloodtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BId', models.CharField(max_length=10)),
                ('Description', models.CharField(max_length=1000)),
                ('point1', models.CharField(max_length=1000)),
                ('point2', models.CharField(max_length=1000)),
                ('point3', models.CharField(max_length=1000)),
                ('point4', models.CharField(max_length=1000)),
                ('point5', models.CharField(max_length=1000)),
                ('point6', models.CharField(max_length=1000)),
                ('Bloodtype', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
