# Generated by Django 4.2.4 on 2023-08-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0016_bloodtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bloodtype',
        ),
    ]
