# Generated by Django 4.2.4 on 2023-08-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0019_donor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
    ]
