# Generated by Django 4.2.4 on 2023-08-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0021_alter_donor_options_alter_donor_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={},
        ),
        migrations.AlterModelManagers(
            name='donor',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='donor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='donor',
            name='confirm_password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=258),
        ),
        migrations.AlterField(
            model_name='donor',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
