# Generated by Django 4.2.4 on 2023-08-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0024_remove_donor_confirm_password_remove_donor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
