# Generated by Django 4.2.4 on 2023-08-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0025_alter_donor_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='donators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('heading', models.CharField(max_length=100)),
                ('content1', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='donor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
