# Generated by Django 4.2.4 on 2023-08-23 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0027_announcements_image_vide'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='announcements',
            table=None,
        ),
    ]
