# Generated by Django 4.2.4 on 2023-08-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0029_alter_donor_options_alter_donor_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
