# Generated by Django 4.2.4 on 2023-08-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0035_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='vide',
        ),
    ]
