# Generated by Django 4.2.4 on 2023-08-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0037_blood_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='historyblood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('points', models.CharField(max_length=250)),
                ('images', models.ImageField(upload_to='media/')),
                ('point1', models.CharField(max_length=200)),
                ('point2', models.CharField(max_length=250)),
                ('point3', models.CharField(max_length=250)),
                ('point4', models.CharField(max_length=250)),
                ('point5', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='media/')),
                ('subhead', models.CharField(max_length=200)),
                ('cnt1', models.CharField(max_length=250)),
                ('cnt2', models.CharField(max_length=250)),
                ('cnt3', models.CharField(max_length=250)),
                ('cnt4', models.CharField(max_length=250)),
                ('cnt5', models.CharField(max_length=250)),
            ],
        ),
    ]
