# Generated by Django 4.2.4 on 2023-08-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0038_historyblood'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic_requirements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='media/')),
                ('points', models.CharField(max_length=350)),
                ('point1', models.CharField(max_length=350)),
                ('point2', models.CharField(max_length=350)),
                ('point3', models.CharField(max_length=350)),
                ('point4', models.CharField(max_length=350)),
                ('point5', models.CharField(max_length=350)),
                ('point6', models.CharField(max_length=350)),
                ('point7', models.CharField(max_length=350)),
                ('point8', models.CharField(max_length=350)),
                ('point9', models.CharField(max_length=350)),
                ('images', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='basicrequirements',
        ),
    ]
