# Generated by Django 4.2.4 on 2023-08-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0039_basic_requirements_delete_basicrequirements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='additional_eligibility',
        ),
        migrations.DeleteModel(
            name='additional_requirements',
        ),
        migrations.DeleteModel(
            name='eligibility',
        ),
    ]
