# Generated by Django 4.2.4 on 2023-08-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0040_delete_additional_eligibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='additional_requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('point2', models.CharField(max_length=1000)),
                ('point3', models.CharField(max_length=1000)),
                ('point4', models.CharField(max_length=1000)),
                ('point5', models.CharField(max_length=1000)),
                ('point6', models.CharField(max_length=1000)),
                ('point7', models.CharField(max_length=1000)),
                ('point8', models.CharField(max_length=1000)),
                ('point9', models.CharField(max_length=1000)),
                ('point1', models.CharField(max_length=1000)),
                ('image1', models.ImageField(upload_to='images/')),
                ('heading', models.CharField(max_length=100)),
            ],
        ),
    ]
