# Generated by Django 4.2.4 on 2023-08-30 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0041_additional_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
    ]
