# Generated by Django 4.2.4 on 2023-09-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0044_lastdonatedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.DeleteModel(
            name='BloodRequest',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
