# Generated by Django 4.2.4 on 2023-09-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0045_remove_notification_recipient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lastdonatedetails',
        ),
    ]
