# Generated by Django 4.2.4 on 2023-09-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0048_alter_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
