# Generated by Django 4.2.4 on 2023-09-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0049_donor_is_eligible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='is_eligible',
        ),
    ]
