# Generated by Django 4.2.1 on 2023-09-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0050_remove_donor_is_eligible'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contactusadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('contactno', models.BigIntegerField()),
                ('website', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('map', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='images/')),
                ('Heading1', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=3000)),
                ('text', models.CharField(default='', max_length=3000)),
                ('point1', models.CharField(default='', max_length=1000)),
                ('point2', models.CharField(default='', max_length=1000)),
                ('point3', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='tips_donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subHeading', models.CharField(max_length=100)),
                ('point1', models.CharField(default='', max_length=1000)),
                ('point2', models.CharField(default='', max_length=1000)),
                ('point3', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='contactus',
            name='enquirytype',
            field=models.CharField(choices=[('Blood Donor', 'Blood Donor'), ('Blood Type', 'Blood Type')], default='Blood Donor', max_length=1000),
        ),
    ]
