# Generated by Django 3.2.20 on 2023-09-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0051_contact_contactusadmin_content_tips_donation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='last_donation_date',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='preferences',
        ),
    ]
