# Generated by Django 3.2.20 on 2023-09-04 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood_donate', '0052_auto_20230904_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aread', models.CharField(max_length=10)),
                ('awrite', models.CharField(max_length=10)),
                ('aupdate', models.CharField(max_length=10)),
                ('aremove', models.CharField(max_length=10)),
                ('aconta', models.CharField(max_length=10)),
                ('mobileno', models.CharField(max_length=10)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood_donate.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
