# Generated by Django 3.2.20 on 2023-09-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0053_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='in_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
